name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  b2-posix:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: show uname
        run: |
          uname -a
      # - name: checkout code
      #   uses: actions/checkout@v4
      #   with:
      #       repository: ffgan/ceph
      #       ref: feature/allow_riscv64_compile
      #       submodules: 'true'

      - name: setup qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: riscv64

      - name: setup docker  Buildx
        uses: docker/setup-buildx-action@v3

      - name: start container
        run: |
          docker run --platform linux/riscv64 -d --name u22 -v ./:/src ubuntu:22.04 bash -c "while true; do sleep 30; done"

      - name: Show uname info
        run: |
          docker exec u22 uname -a
          docker exec u22 cat /etc/os-release
      - name: Download Boost
        run: |
          # https://docs.ceph.com/en/latest/dev/continuous-integration/#build-dependencies
          # download ceph-boost 1.82
          docker exec u22 bash -c "curl http://download.ceph.com/qa/boost_1_82_0.tar.bz2 -o boost_1_82_0.tar.bz2"
          docker exec u22 bash -c "tar xjf boost_1_82_0.tar.bz2 && cd boost_1_82_0 && ls -l "

      - name: b2 -  Setup Boost
        run: |
          docker exec u22 bash -c "cd boost_1_82_0 && ./bootstrap.sh && ./b2 -d0 headers"

      - name: b2 -  Build Boost
        run: |
          docker exec u22 bash -c "cd boost_1_82_0 &&  ./b2 -j64 stage"

      - name: b2 -  Install Boost
        run: |
          docker exec u22 bash -c "cd boost_1_82_0 && ./b2 -j64 --prefix=$HOME/.local install"

      - name: b2 -  Test Boost
        run: |
          docker exec u22 bash -c "cd boost_1_82_0/status && ../b2 -j64 quick && sleep 30"

      - name: Build deb package
        run: |
          docker exec u22 bash -c "apt install -y debhelper-compat dctrl-tools chrpath libbz2-dev liblzma-dev libzstd-dev libicu-dev mpi-default-dev bison flex docbook-to-man help2man xsltproc doxygen dh-python python3-all-dev python3-numpy graphviz dpkg-dev"
          docker exec u22 bash -c "git clone https://github.com/ceph/ceph-boost ; cp -ra ceph-boost/debian boost_1_82_0/ ; pushd boost_1_82_0/;  export DEB_BUILD_OPTIONS='parallel=6 nodoc';  sed -i 's/1.21/1.82/g' debian/control; dpkg-buildpackage -us -uc -b; popd;ls -l"

      - name: Copy deb package
        run: |
          docker cp rv_u24:~/ceph*deb ./

      - name: Show deb package
        run: ls -l

      - name: Upload deb package
        uses: actions/upload-artifact@v4
        with:
          name: ceph-boost-deb
          path: ./ceph*deb
