name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  b2-posix:
    strategy:
      fail-fast: false

    runs-on: self-hosted
    timeout-minutes: 30000
    steps:
      - name: Show uname info
        run: |
          ssh rvu24 uname -a
      - name: Download Boost
        run: |
          # https://docs.ceph.com/en/latest/dev/continuous-integration/#build-dependencies
          # download ceph-boost 1.82
          curl http://download.ceph.com/qa/boost_1_82_0.tar.bz2 -o boost_1_82_0.tar.bz2
          scp boost_1_82_0.tar.bz2 rvu24:~/
          ssh rvu24 " chown root:root boost_1_82_0.tar.bz2 && tar xjf boost_1_82_0.tar.bz2 && cd boost_1_82_0 && ls -l "

      - name: b2 -  Setup Boost
        run: |
          ssh rvu24 "cd boost_1_82_0 && ./bootstrap.sh && ./b2 -d0 headers"

      - name: b2 -  Build Boost
        run: |
          ssh rvu24 "cd boost_1_82_0 &&  ./b2 -j64 stage"

      - name: b2 -  Install Boost
        run: |
          ssh rvu24 "cd boost_1_82_0 && ./b2 -j64 --prefix=$HOME/.local install"

      - name: b2 -  Test Boost
        run: |
          ssh rvu24 "cd boost_1_82_0/status && ../b2 -j64 quick"

      - name: cmake -  Setup Boost
        run: |
          ssh rvu24 "cd boost_1_82_0 && mkdir __build__ && cd __build__ && cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=~/.local .."

      - name: cmake -  Build Boost
        run: |
          ssh rvu24 "cd boost_1_82_0/__build__ &&  cmake --build . -j 64"

      - name: cmake -  Install Boost
        run: |
          ssh rvu24 "cd boost_1_82_0/__build__ && cmake --build . -j 64 --target install"

      - name: cmake -  Test Boost
        run: |
          ssh rvu24 "cd boost_1_82_0/__build && cmake -DBUILD_TESTING=ON .. && cmake --build . -j 64 --target tests && ctest --output-on-failure --no-tests=error -j 64 -R quick"

      - name: Build deb package
        run: |
          ssh rvu24 "git clone https://github.com/ceph/ceph-boost;\
                  cp -ra ceph-boost/debian boost_1_82_0/;\
                  pushd boost_1_82_0/;\
                  export DEB_BUILD_OPTIONS='parallel=6 nodoc';\
                  sed -i 's/1.21/1.82/g' debian/control;\
                  dpkg-buildpackage -us -uc -b;\
                  popd;ls -l"

      - name: Copy deb package
        run: |
          scp rvu24:~/ceph*deb ./

      - name: Show deb package
        run: dir

      - name: Upload deb package
        uses: actions/upload-artifact@v4
        with:
          name: ceph-boost-deb
          path: ./ceph*deb
