name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  b2-posix:
    strategy:
      fail-fast: false

    runs-on: self-hosted

    steps:
      - name: Show uname info
        run: |
          ssh u22 uname -a
      - name: Download Boost
        run: |
          # https://docs.ceph.com/en/latest/dev/continuous-integration/#build-dependencies
          # download ceph-boost 1.82
          ssh u22 "wget http://download.ceph.com/qa/boost_1_82_0.tar.bz2 &&tar xjf boost_1_82_0.tar.bz2 && cd boost_1_82_0 && ls -l "

      - name: Setup Boost
        run: |
          ssh u22 "cd boost_1_82_0 && ./bootstrap.sh && ./b2 -d0 headers"

      - name: Build Boost
        run: |
          ssh u22 "cd boost_1_82_0 &&  ./b2 -j3 stage"

      - name: Install Boost
        run: |
          ssh u22 "cd boost_1_82_0 && ./b2 -j3 --prefix=$HOME/.local install"

      - name: Test Boost
        run: |
          ssh u22 "cd boost_1_82_0/status && ../b2 -j3 quick"
