name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  b2-posix:
    strategy:
      fail-fast: false

    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    steps:
      - name: Show uname info
        run: |
          ssh u22 uname -a
      # - name: Download Boost
      #   run: |
      #     # https://docs.ceph.com/en/latest/dev/continuous-integration/#build-dependencies
      #     # download ceph-boost 1.82
      #     ssh u22 "wget http://download.ceph.com/qa/boost_1_82_0.tar.bz2 &&tar xjf boost_1_82_0.tar.bz2 && cd boost_1_82_0 && ls -l "

      # - name: Setup Boost
      #   run: |
      #     ssh u22 "cd boost_1_82_0 && ./bootstrap.sh && ./b2 -d0 headers"

      # - name: Build Boost
      #   run: |
      #     ssh u22 "cd boost_1_82_0 &&  ./b2 -j3 stage"

      # - name: Install Boost
      #   run: |
      #     ssh u22 "cd boost_1_82_0 && ./b2 -j3 --prefix=$HOME/.local install"

      # - name: Test Boost
      #   run: |
      #     ssh u22 "cd boost_1_82_0/status && ../b2 -j3 quick"

      # - name: Build deb package
      #   run: |
      #     ssh u22 "git clone https://github.com/ceph/ceph-boost;\
      #             cp -ra ceph-boost/debian boost_1_82_0/;\
      #             pushd boost_1_82_0/;\
      #             export DEB_BUILD_OPTIONS='parallel=6 nodoc';\
      #             sed -i 's/1.21/1.82/g' debian/control;\
      #             dpkg-buildpackage -us -uc -b;\
      #             popd;ls -l"

      - name: Copy deb package
        run: |
          scp u22:~/*.deb ./

      - name: Show deb package
        run: ls -l *.deb

      - name: Upload deb package
        uses: actions/upload-artifact@v4
        with:
          name: boost-deb-packages
          path: ./*.deb
